### PR TITLE
add api-key

### PR DESCRIPTION
**Pull request by Langleu**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, here is documentation of api key authentication by the resource api: https://github.com/schul-cloud/resources-api-v1#authorization

**Comment by Langleu** [comment]
I use `x-api-key` as we already use the Authentication field for the JWT and don't want to mix up JWT and API Keys from third party services.

**Comment by niccokunzmann** [comment]
> I use x-api-key as we already use the Authentication field for the JWT 

I understand this.

> don't want to mix up JWT and API Keys from third party services.

In case we use authentiction for the resource api, should we also use your method? Which 3rd party services do you refer to?
>

**Comment by Langleu** [comment]
it is currently only necessary if you intend to use the resolver service.
3rd party services are everything that is currently not in the schulcloud-server, meaning notifications, calendar, ... would be considered a 3rd party service, as it does not have the JWT.

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
